// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:bb14a82e-d29e-4ff2-9fdf-979a2a6c1a93",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_qSNxnU2Vl",
    "aws_user_pools_web_client_id": "6629r5b39kl1dpto3hk2pve73o",
    "aws_user_files_s3_bucket": "amplifyangularfc219c6ffa954a3785aa82c13acc8eea",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "amplify-notes",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
